import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import Badge from "@/components/Badge";
import Icon from "@/components/Icon";
import "@mintlify/mdx/dist/styles.css"


//icons from !! React Icons !!
import { CiSearch } from "react-icons/ci";
import { IoSunnyOutline } from "react-icons/io5";
import { SheetContent } from "@/components/Sheet";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>

      {/** Header of the docs */}
      <div className="flex flex-row place-content-between p-4 border-b border-black/5 fixed z-10 w-[100%] backdrop-blur  bg-[#FDFDFD]">
        <div className="flex flex-row gap-1.5 items-center w-fit mr-4">
          <img width={20} height={20} className="w-[20px]" alt="CreativeRobots" src={"https://dl.dropbox.com/scl/fi/2bxt0v45q4odj1rvxdqo4/Clip-path-group.svg?rlkey=j7y748ujkqvapbybc6wqcyxy8&st=vjtgh475&dl=0"}></img>
          <h1 className="text-base font-[Inter_Display] text-[#1E1F22]">Layouts.dev</h1>
          <Badge className="bg-[#F4F3F1] text-[#ED5F00] font-medium hover:bg-[#f4f3f1] py-1 h-min">Docs</Badge>
        </div>
        <div className="flex flex-row gap-3 items-center flex-1 max-w-72 ml-auto">
          <div className="flex flex-row py-1.5 px-3 gap-1 shadow-sm border border-black/5 w-full rounded-lg bg-white">
            <CiSearch className="w-4 text-black/40" width={16} height={16}/>
            <input type="text" placeholder="Search..." className="text-sm text-black/40 focus:outline-none w-12 flex-1"></input>
          </div>
          <div className="p-2 rounded hover:bg-black/5">
            <IoSunnyOutline className="text-[#1E1F22]" width={16} height={16}/>
          </div>
        </div>
      </div>
      <main className="w-full min-h-full bg-[#FDFDFD]">
        
        <div className='flex flex-row h-full w-full justify-center relative gap-0'>
          <div className='w-72 hidden md:block sticky top-0  h-screen p-2 pt-[122px] pl-8 overflow-y-scroll'>
              <SheetContent/>
          </div>
          {children}
        </div>
      </main>
      <div className="border-t h-20 bg-[#FDFDFD]">

      </div>
      </body>
    </html>
  );
}
